swagger: "2.0"
info:
  description: ""
  version: 1.0.0
  title: verify-u API
tags:
  - name: identifications
    description: ""
  - name: documents
    description: ""
schemes:
  - https
  - http
paths:
  /identifications:
    $ref: paths/identifications.yaml
  /identifications/{id}:
    $ref: paths/identifications_id.yaml
  /identifications/iddocument/{id}:
    $ref: paths/identifications_iddocument_id.yaml
  /identifications/video/{id}:
    $ref: paths/identifications_video_id.yaml
  /identifications/esign/{id}:
    $ref: paths/identifications_esign_id.yaml
  /documents/create:
    $ref: paths/documents_create.yaml
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

host: verify-u.com
basePath: /api
